language: php

sudo: false

php:
  - 8.2

before_script:
  - composer self-update
  - composer install --prefer-dist --no-interaction
script:
  - chmod -R 777 tests/build
  - ./vendor/bin/phpunit --coverage-clover tests/logs/clover.xml
after_script:
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.3" ]]; then php ./vendor/bin/php-coveralls -v; fi
