<?php

/**
 * Qubus\ValueObjects
 *
 * @link       https://github.com/QubusPHP/valueobjects
 * @copyright  2020
 * @author     Joshua Parker <joshua@joshuaparker.dev>
 * @license    https://opensource.org/licenses/mit-license.php MIT License
 *
 * @since      1.0.0
 */

declare(strict_types=1);

namespace Qubus\ValueObjects\Money;

use Qubus\ValueObjects\Enum\Enum;

/**
 * @method static string AED()
 * @method static string AFN()
 * @method static string ALL()
 * @method static string AMD()
 * @method static string ANG()
 * @method static string AOA()
 * @method static string ARS()
 * @method static string AUD()
 * @method static string AWG()
 * @method static string AZN()
 * @method static string BAM()
 * @method static string BBD()
 * @method static string BDT()
 * @method static string BGN()
 * @method static string BHD()
 * @method static string BIF()
 * @method static string BMD()
 * @method static string BND()
 * @method static string BOB()
 * @method static string BRL()
 * @method static string BSD()
 * @method static string BTN()
 * @method static string BWP()
 * @method static string BYR()
 * @method static string BZD()
 * @method static string CAD()
 * @method static string CDF()
 * @method static string CHF()
 * @method static string CLF()
 * @method static string CLP()
 * @method static string CNY()
 * @method static string COP()
 * @method static string CRC()
 * @method static string CUP()
 * @method static string CVE()
 * @method static string CZK()
 * @method static string DJF()
 * @method static string DKK()
 * @method static string DOP()
 * @method static string DZD()
 * @method static string EEK()
 * @method static string EGP()
 * @method static string ETB()
 * @method static string EUR()
 * @method static string FJD()
 * @method static string FKP()
 * @method static string GBP()
 * @method static string GEL()
 * @method static string GHS()
 * @method static string GIP()
 * @method static string GMD()
 * @method static string GNF()
 * @method static string GTQ()
 * @method static string GYD()
 * @method static string HKD()
 * @method static string HNL()
 * @method static string HRK()
 * @method static string HTG()
 * @method static string HUF()
 * @method static string IDR()
 * @method static string ILS()
 * @method static string INR()
 * @method static string IQD()
 * @method static string IRR()
 * @method static string ISK()
 * @method static string JEP()
 * @method static string JMD()
 * @method static string JOD()
 * @method static string JPY()
 * @method static string KES()
 * @method static string KGS()
 * @method static string KHR()
 * @method static string KMF()
 * @method static string KPW()
 * @method static string KRW()
 * @method static string KWD()
 * @method static string KYD()
 * @method static string KZT()
 * @method static string LAK()
 * @method static string LBP()
 * @method static string LKR()
 * @method static string LRD()
 * @method static string LSL()
 * @method static string LTL()
 * @method static string LVL()
 * @method static string LYD()
 * @method static string MAD()
 * @method static string MDL()
 * @method static string MGA()
 * @method static string MKD()
 * @method static string MMK()
 * @method static string MNT()
 * @method static string MOP()
 * @method static string MRO()
 * @method static string MUR()
 * @method static string MVR()
 * @method static string MWK()
 * @method static string MXN()
 * @method static string MYR()
 * @method static string MZN()
 * @method static string NAD()
 * @method static string NGN()
 * @method static string NIO()
 * @method static string NOK()
 * @method static string NPR()
 * @method static string NZD()
 * @method static string OMR()
 * @method static string PAB()
 * @method static string PEN()
 * @method static string PGK()
 * @method static string PHP()
 * @method static string PKR()
 * @method static string PLN()
 * @method static string PYG()
 * @method static string QAR()
 * @method static string RON()
 * @method static string RSD()
 * @method static string RUB()
 * @method static string RWF()
 * @method static string SAR()
 * @method static string SBD()
 * @method static string SCR()
 * @method static string SDG()
 * @method static string SEK()
 * @method static string SGD()
 * @method static string SHP()
 * @method static string SLL()
 * @method static string SOS()
 * @method static string SRD()
 * @method static string STD()
 * @method static string SVC()
 * @method static string SYP()
 * @method static string SZL()
 * @method static string THB()
 * @method static string TJS()
 * @method static string TMT()
 * @method static string TND()
 * @method static string TOP()
 * @method static string TRY_()
 * @method static string TTD()
 * @method static string TWD()
 * @method static string TZS()
 * @method static string UAH()
 * @method static string UGX()
 * @method static string USD()
 * @method static string UYU()
 * @method static string UZS()
 * @method static string VEF()
 * @method static string VND()
 * @method static string VUV()
 * @method static string WST()
 * @method static string XAF()
 * @method static string XCD()
 * @method static string XDR()
 * @method static string XOF()
 * @method static string XPF()
 * @method static string YER()
 * @method static string ZAR()
 * @method static string ZMK()
 * @method static string ZWL()
 */
class CurrencyCode extends Enum
{
    public const AED = 'AED';
    public const AFN = 'AFN';
    public const ALL = 'ALL';
    public const AMD = 'AMD';
    public const ANG = 'ANG';
    public const AOA = 'AOA';
    public const ARS = 'ARS';
    public const AUD = 'AUD';
    public const AWG = 'AWG';
    public const AZN = 'AZN';
    public const BAM = 'BAM';
    public const BBD = 'BBD';
    public const BDT = 'BDT';
    public const BGN = 'BGN';
    public const BHD = 'BHD';
    public const BIF = 'BIF';
    public const BMD = 'BMD';
    public const BND = 'BND';
    public const BOB = 'BOB';
    public const BRL = 'BRL';
    public const BSD = 'BSD';
    public const BTN = 'BTN';
    public const BWP = 'BWP';
    public const BYR = 'BYR';
    public const BZD = 'BZD';
    public const CAD = 'CAD';
    public const CDF = 'CDF';
    public const CHF = 'CHF';
    public const CLF = 'CLF';
    public const CLP = 'CLP';
    public const CNY = 'CNY';
    public const COP = 'COP';
    public const CRC = 'CRC';
    public const CUP = 'CUP';
    public const CVE = 'CVE';
    public const CZK = 'CZK';
    public const DJF = 'DJF';
    public const DKK = 'DKK';
    public const DOP = 'DOP';
    public const DZD = 'DZD';
    public const EEK = 'EEK';
    public const EGP = 'EGP';
    public const ETB = 'ETB';
    public const EUR = 'EUR';
    public const FJD = 'FJD';
    public const FKP = 'FKP';
    public const GBP = 'GBP';
    public const GEL = 'GEL';
    public const GHS = 'GHS';
    public const GIP = 'GIP';
    public const GMD = 'GMD';
    public const GNF = 'GNF';
    public const GTQ = 'GTQ';
    public const GYD = 'GYD';
    public const HKD = 'HKD';
    public const HNL = 'HNL';
    public const HRK = 'HRK';
    public const HTG = 'HTG';
    public const HUF = 'HUF';
    public const IDR = 'IDR';
    public const ILS = 'ILS';
    public const INR = 'INR';
    public const IQD = 'IQD';
    public const IRR = 'IRR';
    public const ISK = 'ISK';
    public const JEP = 'JEP';
    public const JMD = 'JMD';
    public const JOD = 'JOD';
    public const JPY = 'JPY';
    public const KES = 'KES';
    public const KGS = 'KGS';
    public const KHR = 'KHR';
    public const KMF = 'KMF';
    public const KPW = 'KPW';
    public const KRW = 'KRW';
    public const KWD = 'KWD';
    public const KYD = 'KYD';
    public const KZT = 'KZT';
    public const LAK = 'LAK';
    public const LBP = 'LBP';
    public const LKR = 'LKR';
    public const LRD = 'LRD';
    public const LSL = 'LSL';
    public const LTL = 'LTL';
    public const LVL = 'LVL';
    public const LYD = 'LYD';
    public const MAD = 'MAD';
    public const MDL = 'MDL';
    public const MGA = 'MGA';
    public const MKD = 'MKD';
    public const MMK = 'MMK';
    public const MNT = 'MNT';
    public const MOP = 'MOP';
    public const MRO = 'MRO';
    public const MUR = 'MUR';
    public const MVR = 'MVR';
    public const MWK = 'MWK';
    public const MXN = 'MXN';
    public const MYR = 'MYR';
    public const MZN = 'MZN';
    public const NAD = 'NAD';
    public const NGN = 'NGN';
    public const NIO = 'NIO';
    public const NOK = 'NOK';
    public const NPR = 'NPR';
    public const NZD = 'NZD';
    public const OMR = 'OMR';
    public const PAB = 'PAB';
    public const PEN = 'PEN';
    public const PGK = 'PGK';
    public const PHP = 'PHP';
    public const PKR = 'PKR';
    public const PLN = 'PLN';
    public const PYG = 'PYG';
    public const QAR = 'QAR';
    public const RON = 'RON';
    public const RSD = 'RSD';
    public const RUB = 'RUB';
    public const RWF = 'RWF';
    public const SAR = 'SAR';
    public const SBD = 'SBD';
    public const SCR = 'SCR';
    public const SDG = 'SDG';
    public const SEK = 'SEK';
    public const SGD = 'SGD';
    public const SHP = 'SHP';
    public const SLL = 'SLL';
    public const SOS = 'SOS';
    public const SRD = 'SRD';
    public const STD = 'STD';
    public const SVC = 'SVC';
    public const SYP = 'SYP';
    public const SZL = 'SZL';
    public const THB = 'THB';
    public const TJS = 'TJS';
    public const TMT = 'TMT';
    public const TND = 'TND';
    public const TOP = 'TOP';
    public const TRY_ = 'TRY'; // "try" is a PHP reserved word
    public const TTD = 'TTD';
    public const TWD = 'TWD';
    public const TZS = 'TZS';
    public const UAH = 'UAH';
    public const UGX = 'UGX';
    public const USD = 'USD';
    public const UYU = 'UYU';
    public const UZS = 'UZS';
    public const VEF = 'VEF';
    public const VND = 'VND';
    public const VUV = 'VUV';
    public const WST = 'WST';
    public const XAF = 'XAF';
    public const XCD = 'XCD';
    public const XDR = 'XDR';
    public const XOF = 'XOF';
    public const XPF = 'XPF';
    public const YER = 'YER';
    public const ZAR = 'ZAR';
    public const ZMK = 'ZMK';
    public const ZWL = 'ZWL';
}
